DEFAULT_EXCLUDES = {
    # Стандартные исключения для веб-приложений
    'node_modules',
    '.git',
    'venv',
    '.env',
    '__pycache__',
    'dist',
    'build',
    '.next',
    '.idea',
    '.vscode',
    'coverage',
    '.pytest_cache',
    '.cache',
    'tmp',
    'temp',
    'logs',
    '.DS_Store',
    'package-lock.json',
    'yarn.lock',
    '.gitignore',
    '.env.local',
    '.env.development',
    '.env.production',
    
    # .NET разработка
    'bin',
    'obj',
    'nupkg',
    'nupkgs',
    'nupkgsс',
    'PublishProfiles',
    'Properties/PublishProfiles',
    '.vs',
    'TestResults',
    'packages',
    'artifacts',
    
    # Временные файлы и кэш
    '.user',
    '.cache',
    '.suo',
    '.userprefs',
    '.usertasks',
    '.docstates',
    '.dbmdl',
    '.jfm',
    '.pfx',
    '.publishsettings',
    '.pubxml',
    '.pubxml.user',
    
    # Логи и отладка
    '*.log',
    'debug',
    'Debug',
    'release',
    'Release',
    'x64',
    'x86',
    
    # Резервные копии
    '*.bak',
    '*.backup',
    '*~',
    '*.swp',
    
    # Специфичные для IDE
    '.project',
    '.classpath',
    '.settings',
    '*.sublime-workspace',
    '*.sublime-project',
    '.editorconfig',
    
    # Метаданные
    '.metadata',
    '.svn',
    '.hg',
    'CVS',
    'thumbs.db',
    'desktop.ini',
} 